# Generated by Django 5.2 on 2025-04-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieInfo',
            new_name='MovieInformation',
        ),
    ]
