# Generated by Django 5.2 on 2025-04-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_rename_movieinfo_movieinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInformationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='movies/posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MovieInformation',
        ),
    ]
